### DISCUSSION TITLE
how to main with header without 100vh ?

### DISCUSSION THREAD

**Discussion by jsupa** [beercss/beercss#292] [General]
I'm trying to remove the scrollbar

Its possible remove `min-block-size: 100vh` from `main.responsive` ? if I have 

```pug
body
    header.fixed
    main.responsive
```

**Comment by leonardorafael** [comment]
We can't remove that, this will break footer and centered layouts. But there are some ways to do that:

Add a `no-scroll` helper:

```pug
body.no-scroll
    header.fixed
    main.responsive
```

Or a custom CSS:

```css
main.responsive {
  min-block-size: auto;
}
```

**Comment by jsupa** [comment]
Ok, thanks I'll use custom css.

```css
main.responsive {
    min-block-size: calc(100dvh - 4rem) !important;
}
```
