### ISSUE TITLE
field label should be moved by focus instead of active attribute

### ISSUE THREAD

**Issue by laurentpayot** [beercss/beercss#15]
Having to add an `active` attribute to the `label` tags of my fields is a major pain because it means handling the focus state of every field in my front-end framework ([Elm](https://elm-lang.org/)).

I could not find a reason why the label should not be moved to the top when the field is focused (and the cursor is blinking in the input, covering half the label). 

It could simply be done with the following [selector change in field.css](https://github.com/beercss/beercss/blob/e102e1a967c6a0d6dd30d5860a6d532b3d97578d/src/cdn/shared/fields.css#L290):
```css
.field.label > input:focus ~ label {
  animation: 0.1s label-to-top;
  font-size: 12rem;
  transform: translateY(-120%);
}
```
Feel free to ask for a PR if needed.

Cheers

**Comment by laurentpayot** [comment]
Ah I just found out that the label goes down when the field is unfocused :man_facepalming: Looking for another fix :wink:

**Comment by laurentpayot** [comment]
I ended-up adding two selectors to make it work: 
```css
.field.label > label.active,
.field.label > input:focus ~ label,
.field.label > input:not(:placeholder-shown) ~ label,
 {
  animation: 0.1s label-to-top;
  font-size: 12rem;
  transform: translateY(-120%);
}
```
Do you think it should be added to beercss?
