### ISSUE TITLE
CSS-only dropdowns

### ISSUE THREAD

**Issue by laurentpayot** [beercss/beercss#16]
In the same spirit as #15, to avoid the burden of adding/removing the `active` class in dropdowns with JavaScript, I added two CSS selectors to the [dropdowns.css active section](https://github.com/beercss/beercss/blob/e102e1a967c6a0d6dd30d5860a6d532b3d97578d/src/cdn/shared/dropdowns.css#L30):
```css
.dropdown.active,
button:focus > .dropdown,
.dropdown:active /* needed for the click events to work */
{
  opacity: 1;
  visibility: visible;
  max-width: none;
  animation: 0.1s dropdown-to-bottom;
}
```
I also added the following CSS for tooltips not to be displayed when the dropdown is shown:
```css
button:focus > .dropdown ~ .tooltip,
.dropdown:active ~ .tooltip
{
  display: none;
}
```
(note that the tooltip `div` has to be after the dropdown) 

You can see the result at https://codepen.io/laurentpayot/pen/vYZPNOQ

Do you think these small changes could be added to beercss too? That would make my day.

Cheers,
Laurent
