### ISSUE TITLE
textarea has a wrong padding-top on focus

### ISSUE THREAD

**Issue by luissardon** [beercss/beercss#200]
Noticed that padding top doesn't align when the element is on focus state:

![placeholder-focus](https://github.com/beercss/beercss/assets/4295163/f19f87cb-e2ef-4a47-8eb8-4816dee1a4d7)

I'm adding this temp fix in my project where I'm only using the border variant, although, you might need to do something similar for all of them, because this isn't happening just with border, but all:

```css
.field.small.border:not(.fill) > textarea:focus {
  padding-top: 0.5625rem !important;
}

.field.border:not(.fill) > textarea:focus {
  padding-top: 0.8125rem !important;
}

.field.large.border:not(.fill) > textarea:focus {
  padding-top: 1.0625rem !important;
}

.field.extra.border:not(.fill) > textarea:focus {
  padding-top: 1.3125rem !important;
}
```
