### ISSUE TITLE
Idea about hovering effect helpers and responsive helpers

### ISSUE THREAD

**Issue by FirokOtaku** [beercss/beercss#327]
I just wonder how do you think about some helpers like `.red-hover`/`.primary-hover`/`.primary-hover-text`. Will you think this is a very narrow use case that does not worth the disk space to be covered at mainline of this lib?

```css
.red-hover:hover {
  background-color: red !important;
}
.red-hover-text:hover {
  color: red !important;
}
.primary-hover:hover {
  background-color: var(--primary) !important;
}
.primary-hover-text:hover {
  color: var(--primary) !important;
}
```

----

BTW, how do you think of this [PR](https://github.com/beercss/beercss/pull/234)? That PR seems automatically closed by branch changes and does not get responses.

**Comment by leonardorafael** [comment]
Hi @FirokOtaku ,

We need to think about it. I don't have any idea how to do that in a "nice way".

Your PR was deleted (because the develop branch was deleted accidentally 😅).

But I think you can use the `small`, `medium`, `large` helpers on `dialog` element. They will respect the viewport area.

**Comment by FirokOtaku** [comment]
> I don't have any idea how to do that in a "nice way".

Maybe we can nest them all together?

```css
:hover
{
  &.red-hover {
    background-color: red !important;
  }
  &.green-hover {
    background-color: green !important;
  }
  ...
}
```

> But I think you can use the small, medium, large helpers on dialog element. They will respect the viewport area.

`.small`, `.medium` and `.large` helpers are giving limitation to container size, which is a different functionality to "responsive layout" I think.
