### ISSUE TITLE
MD3 navigation drawer active indicator

### ISSUE THREAD

**Issue by laurentpayot** [beercss/beercss#33]
From MD3 specs: https://m3.material.io/components/navigation-drawer/guidelines#31eeff65-f988-4951-9cbc-223e2ba2d1b6

For my app I simply had to add the following CSS:
```css
.modal.left a.row.active {
  background-color: var(--active);
}
```
