### ISSUE TITLE
Vertical button row with border has wrong border (with possible fix)

### ISSUE THREAD

**Issue by AlTrAugsburg** [beercss/beercss#392]
Hi there,

if I create a vertical row with the class "no-space" and three bordered buttons, the button in the middle and the bottom, have no border on the left side, like here:

![Screenshot From 2024-12-04 19-37-31](https://github.com/user-attachments/assets/6145d232-dc6a-44e7-88db-64ef5786e3e2)

On the picture is also visible, what I expected (the fixed version).

The corresponding codepen: https://codepen.io/AlTrAugsburg/pen/PwYZYQB

I fixed it in my project with the following CSS-Code:

```css
:is(nav, .row).no-space.vertical > .border + .border {
  border-inline-start: .0625rem solid var(--outline);
  border-top: 0;
}
```

First line "overwrites" the setting from `:is(nav, .row).no-space > .border + .border` and the second one removes the top border, so it looks like one consistent border.
